// ベビーシッターサービスのモックデータ
const SITTER_SERVICES = [
  {
    id: 1,
    name: "キッズパートナー",
    logo: "KP",
    logoColor: "#FF6B9D",
    description: "保育士資格を持つシッターが多数在籍。安心と信頼の保育サービスを提供します。",
    pricePerHour: 1800,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.7,
    reviewCount: 342,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区"],
    ageRange: "0歳〜12歳",
    tags: ["保育士資格", "当日予約OK", "送迎あり"],
    features: ["全シッター保育士資格保有", "当日2時間前まで予約OK", "保育園・習い事への送迎", "定期利用割引あり", "Web予約で即日対応"],
    availableNow: 8,
    availableToday: 15,
    availableTomorrow: 22,
    operatingHours: "7:00〜22:00",
    cancellationPolicy: "前日18時まで無料キャンセル",
    insurance: "対人・対物賠償保険加入済み",
    url: "#"
  },
  {
    id: 2,
    name: "マザーズヘルパー東京",
    logo: "MH",
    logoColor: "#4ECDC4",
    description: "家事代行も同時にお願いできる忙しいママの味方。食事の準備や掃除もおまかせ。",
    pricePerHour: 2200,
    minimumHours: 3,
    registrationFee: 5500,
    annualFee: 0,
    rating: 4.5,
    reviewCount: 218,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区"],
    ageRange: "0歳〜10歳",
    tags: ["家事代行", "保育士資格", "送迎あり"],
    features: ["保育+家事代行セットプラン", "栄養士監修の食事準備", "保育園お迎え対応", "月額プランでお得", "家庭の衛生管理も対応"],
    availableNow: 5,
    availableToday: 12,
    availableTomorrow: 18,
    operatingHours: "8:00〜21:00",
    cancellationPolicy: "前日12時まで無料キャンセル",
    insurance: "総合賠償保険加入済み",
    url: "#"
  },
  {
    id: 3,
    name: "バイリンガルキッズ",
    logo: "BK",
    logoColor: "#6C5CE7",
    description: "英語でのベビーシッティング。遊びながら自然に英語力を育てます。",
    pricePerHour: 2800,
    minimumHours: 2,
    registrationFee: 11000,
    annualFee: 5500,
    rating: 4.8,
    reviewCount: 156,
    areas: ["渋谷区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区"],
    ageRange: "1歳〜12歳",
    tags: ["英語対応", "保育士資格"],
    features: ["ネイティブ・バイリンガルシッター", "英語で遊びながら学べる", "フォニックス学習対応", "インターナショナルスクール送迎", "レッスンレポート付き"],
    availableNow: 3,
    availableToday: 8,
    availableTomorrow: 14,
    operatingHours: "8:00〜20:00",
    cancellationPolicy: "2日前まで無料キャンセル",
    insurance: "賠償責任保険加入済み",
    url: "#"
  },
  {
    id: 4,
    name: "ほっとシッター",
    logo: "HS",
    logoColor: "#FD7272",
    description: "病児保育専門。お子さまの急な体調不良に対応できる看護師資格保有のシッター。",
    pricePerHour: 2500,
    minimumHours: 3,
    registrationFee: 3300,
    annualFee: 0,
    rating: 4.9,
    reviewCount: 89,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "文京区", "豊島区"],
    ageRange: "0歳〜8歳",
    tags: ["病児保育", "保育士資格", "当日予約OK"],
    features: ["看護師・保育士のダブル資格", "37.5度以上の発熱時も対応", "感染症対応可", "かかりつけ医との連携", "当日朝8時まで予約OK"],
    availableNow: 4,
    availableToday: 9,
    availableTomorrow: 11,
    operatingHours: "7:00〜20:00",
    cancellationPolicy: "当日朝6時まで無料キャンセル",
    insurance: "医療過誤保険・賠償保険加入済み",
    url: "#"
  },
  {
    id: 5,
    name: "スマイルシッター",
    logo: "SS",
    logoColor: "#F8A5C2",
    description: "リーズナブルな料金設定で、初めてのシッター利用にもおすすめ。",
    pricePerHour: 1500,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.3,
    reviewCount: 567,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["当日予約OK"],
    features: ["業界最安水準の料金", "入会金・年会費無料", "アプリで簡単予約", "シッターのプロフィール閲覧可", "初回30分無料お試し"],
    availableNow: 12,
    availableToday: 28,
    availableTomorrow: 35,
    operatingHours: "7:00〜23:00",
    cancellationPolicy: "前日20時まで無料キャンセル",
    insurance: "対人賠償保険加入済み",
    url: "#"
  },
  {
    id: 6,
    name: "ナニーサービス東京",
    logo: "NS",
    logoColor: "#45B7D1",
    description: "専属シッター制度で同じシッターに継続依頼。お子さまとの信頼関係を大切に。",
    pricePerHour: 3000,
    minimumHours: 3,
    registrationFee: 22000,
    annualFee: 11000,
    rating: 4.8,
    reviewCount: 124,
    areas: ["渋谷区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区"],
    ageRange: "0歳〜6歳",
    tags: ["保育士資格", "送迎あり", "英語対応"],
    features: ["専属シッター担当制", "保育計画書の作成", "月間保育レポート", "食育対応の食事準備", "英語対応シッターも選択可"],
    availableNow: 2,
    availableToday: 5,
    availableTomorrow: 8,
    operatingHours: "7:00〜21:00",
    cancellationPolicy: "3日前まで無料キャンセル",
    insurance: "総合賠償保険・傷害保険加入済み",
    url: "#"
  },
  {
    id: 7,
    name: "ぽぽらシッター",
    logo: "PP",
    logoColor: "#FECA57",
    description: "地域密着型のシッターサービス。ご近所のシッターが駆けつけます。",
    pricePerHour: 1600,
    minimumHours: 1,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.4,
    reviewCount: 289,
    areas: ["世田谷区", "杉並区", "練馬区", "中央区", "豊島区", "文京区"],
    ageRange: "0歳〜10歳",
    tags: ["当日予約OK", "送迎あり"],
    features: ["最短1時間から利用OK", "地域密着で到着が早い", "ご近所シッターマッチング", "兄弟割引あり", "LINEで簡単予約"],
    availableNow: 6,
    availableToday: 14,
    availableTomorrow: 20,
    operatingHours: "8:00〜22:00",
    cancellationPolicy: "当日2時間前まで無料キャンセル",
    insurance: "対人賠償保険加入済み",
    url: "#"
  },
  {
    id: 8,
    name: "プレミアケア",
    logo: "PC",
    logoColor: "#C8A2C8",
    description: "ホテル品質のベビーシッティング。特別な日や大切なイベント時に。",
    pricePerHour: 3500,
    minimumHours: 3,
    registrationFee: 33000,
    annualFee: 16500,
    rating: 4.9,
    reviewCount: 67,
    areas: ["渋谷区", "港区", "中央区", "千代田区"],
    ageRange: "0歳〜12歳",
    tags: ["保育士資格", "英語対応", "送迎あり", "家事代行"],
    features: ["元幼稚園教諭・保育士のプロ集団", "イベント時の出張保育", "ホテル・レストランへの同行", "フルバイリンガル対応", "24時間コンシェルジュ対応"],
    availableNow: 1,
    availableToday: 4,
    availableTomorrow: 7,
    operatingHours: "24時間対応",
    cancellationPolicy: "3日前まで無料キャンセル",
    insurance: "プレミアム総合保険加入済み",
    url: "#"
  },
  {
    id: 9,
    name: "ワーママシッター",
    logo: "WM",
    logoColor: "#26DE81",
    description: "在宅ワークのママを応援。お子さまを見守りながら仕事に集中できます。",
    pricePerHour: 1700,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.6,
    reviewCount: 198,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "杉並区", "練馬区", "豊島区"],
    ageRange: "0歳〜6歳",
    tags: ["当日予約OK"],
    features: ["在宅ワーク中の保育に特化", "静かに遊べるプログラム", "お昼寝サポート", "テレワーク応援割引", "定期利用で月額15%OFF"],
    availableNow: 7,
    availableToday: 16,
    availableTomorrow: 24,
    operatingHours: "8:00〜20:00",
    cancellationPolicy: "前日18時まで無料キャンセル",
    insurance: "対人賠償保険加入済み",
    url: "#"
  },
  {
    id: 10,
    name: "キッズシールド",
    logo: "KS",
    logoColor: "#3498DB",
    description: "安全管理を最重視。GPS追跡や定期報告でいつでもお子さまの様子がわかります。",
    pricePerHour: 2000,
    minimumHours: 2,
    registrationFee: 5500,
    annualFee: 3300,
    rating: 4.7,
    reviewCount: 176,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "江東区"],
    ageRange: "0歳〜10歳",
    tags: ["保育士資格", "送迎あり", "当日予約OK"],
    features: ["GPS見守りシステム", "30分ごとの写真レポート", "全シッター犯罪歴チェック済み", "AED・応急手当研修修了", "24時間サポートダイヤル"],
    availableNow: 6,
    availableToday: 13,
    availableTomorrow: 19,
    operatingHours: "7:00〜22:00",
    cancellationPolicy: "前日15時まで無料キャンセル",
    insurance: "総合賠償保険・傷害保険加入済み",
    url: "#"
  },
  {
    id: 11,
    name: "おそとあそびシッター",
    logo: "OA",
    logoColor: "#E17055",
    description: "公園遊びや自然体験を重視。お外で思いっきり遊ぶ保育スタイルです。",
    pricePerHour: 1900,
    minimumHours: 2,
    registrationFee: 3300,
    annualFee: 0,
    rating: 4.5,
    reviewCount: 143,
    areas: ["世田谷区", "杉並区", "練馬区", "目黒区", "大田区"],
    ageRange: "1歳〜8歳",
    tags: ["保育士資格", "送迎あり"],
    features: ["公園・自然体験プログラム", "体を動かす遊び重視", "季節の自然遊び", "近隣公園マップ提供", "雨天時は室内遊びに切替"],
    availableNow: 4,
    availableToday: 10,
    availableTomorrow: 16,
    operatingHours: "9:00〜18:00",
    cancellationPolicy: "前日20時まで無料キャンセル",
    insurance: "野外活動賠償保険加入済み",
    url: "#"
  },
  {
    id: 12,
    name: "夜間シッターズ",
    logo: "YS",
    logoColor: "#2C3E50",
    description: "夜間・深夜対応専門。急な残業や夜のお出かけ時に安心してお任せください。",
    pricePerHour: 2300,
    minimumHours: 3,
    registrationFee: 5500,
    annualFee: 0,
    rating: 4.6,
    reviewCount: 91,
    areas: ["渋谷区", "新宿区", "港区", "品川区", "中央区", "千代田区", "豊島区"],
    ageRange: "0歳〜10歳",
    tags: ["当日予約OK", "保育士資格"],
    features: ["18時〜翌朝対応", "お泊まり保育可能", "夜間の授乳・ミルク対応", "寝かしつけのプロ", "急な残業時の駆けつけ対応"],
    availableNow: 3,
    availableToday: 7,
    availableTomorrow: 12,
    operatingHours: "18:00〜翌8:00",
    cancellationPolicy: "当日14時まで無料キャンセル",
    insurance: "24時間対応賠償保険加入済み",
    url: "#"
  },
  {
    id: 13,
    name: "ペアレンツサポート",
    logo: "PS",
    logoColor: "#00B894",
    description: "産後ケア・育児相談もできるシッターサービス。新米ママの心強い味方です。",
    pricePerHour: 2100,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.7,
    reviewCount: 205,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "文京区"],
    ageRange: "0歳〜3歳",
    tags: ["保育士資格", "病児保育"],
    features: ["産後ドゥーラ資格保有者在籍", "沐浴サポート", "育児相談・アドバイス", "母乳育児サポート", "産後うつ傾向の見守り"],
    availableNow: 5,
    availableToday: 11,
    availableTomorrow: 17,
    operatingHours: "8:00〜20:00",
    cancellationPolicy: "前日18時まで無料キャンセル",
    insurance: "総合賠償保険加入済み",
    url: "#"
  },
  {
    id: 14,
    name: "エデュケアシッター",
    logo: "EC",
    logoColor: "#A29BFE",
    description: "教育特化型シッター。知育遊びや学習サポートでお子さまの成長を促します。",
    pricePerHour: 2400,
    minimumHours: 2,
    registrationFee: 11000,
    annualFee: 5500,
    rating: 4.6,
    reviewCount: 112,
    areas: ["渋谷区", "港区", "目黒区", "世田谷区", "中央区", "千代田区", "文京区"],
    ageRange: "2歳〜12歳",
    tags: ["保育士資格", "英語対応"],
    features: ["モンテッソーリ教育対応", "知育玩具を持参", "小学校受験サポート", "英語での保育も可能", "保育レポート・発達記録"],
    availableNow: 3,
    availableToday: 8,
    availableTomorrow: 13,
    operatingHours: "9:00〜20:00",
    cancellationPolicy: "2日前まで無料キャンセル",
    insurance: "賠償責任保険加入済み",
    url: "#"
  },
  {
    id: 15,
    name: "ファミリーコネクト",
    logo: "FC",
    logoColor: "#E84393",
    description: "シッター同士のコミュニティが充実。口コミと信頼で選べるマッチングサービス。",
    pricePerHour: 1650,
    minimumHours: 1,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.4,
    reviewCount: 423,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["当日予約OK", "送迎あり"],
    features: ["口コミ評価で選べる", "シッター面談制度", "1時間からOK", "兄弟姉妹割引20%OFF", "リピーター特典あり"],
    availableNow: 9,
    availableToday: 20,
    availableTomorrow: 30,
    operatingHours: "7:00〜23:00",
    cancellationPolicy: "前日20時まで無料キャンセル",
    insurance: "対人対物賠償保険加入済み",
    url: "#"
  }
];
