// 東京で利用できるベビーシッターサービスの情報
// ※ 料金・サービス内容は変更される場合があります。最新情報は各公式サイトでご確認ください。
const SITTER_SERVICES = [
  {
    id: 1,
    name: "キッズライン",
    logo: "KL",
    logoColor: "#FF6B9D",
    description: "国内最大級のベビーシッターマッチングサービス。入会金・年会費無料で、アプリから簡単に予約できます。",
    pricePerHour: 2200,
    minimumHours: 1,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.5,
    reviewCount: 15000,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["当日予約OK", "家事代行", "病児保育", "送迎あり", "保育士資格"],
    features: ["入会金・年会費完全無料", "アプリで検索から予約・決済まで完結", "内閣府ベビーシッター券・東京都補助制度対応", "家事代行にも対応可能なサポーター在籍", "マッチング型で自分でサポーターを選べる"],
    availableNow: 25,
    availableToday: 60,
    availableTomorrow: 85,
    operatingHours: "24時間対応",
    cancellationPolicy: "48時間前まで無料、24〜48時間前は50%、24時間以内は100%",
    insurance: "損害保険ジャパン 対人・対物賠償責任保険加入済み",
    url: "https://kidsline.me"
  },
  {
    id: 2,
    name: "ポピンズシッター",
    logo: "PS",
    logoColor: "#4ECDC4",
    description: "旧スマートシッター。シッターの90%以上が保育士・幼稚園教諭等の有資格者。30分から利用可能。",
    pricePerHour: 2200,
    minimumHours: 1,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.6,
    reviewCount: 8500,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜18歳",
    tags: ["保育士資格", "送迎あり", "当日予約OK", "病児保育"],
    features: ["シッターの90%以上が保育士・幼稚園教諭等の有資格者", "入会金・年会費無料のマッチング型", "4,000名以上のシッターが登録", "東京都ベビーシッター利用支援事業対応（年間最大36万円補助）", "30分から利用可能で柔軟性が高い"],
    availableNow: 18,
    availableToday: 45,
    availableTomorrow: 70,
    operatingHours: "24時間対応",
    cancellationPolicy: "前々日まで無料、前日17時まで50%、前日17時以降は100%",
    insurance: "賠償責任保険加入済み",
    url: "https://smartsitter.jp"
  },
  {
    id: 3,
    name: "ル・アンジェ",
    logo: "LA",
    logoColor: "#6C5CE7",
    description: "専属シッター制の派遣型サービス。病児保育の派遣率98.3%。産後ケア・新生児ケアにも対応。",
    pricePerHour: 2500,
    minimumHours: 2,
    registrationFee: 55000,
    annualFee: 11000,
    rating: 4.7,
    reviewCount: 2800,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["保育士資格", "病児保育", "送迎あり", "家事代行"],
    features: ["専属シッター制の派遣型で安心感が高い", "病児保育対応 シッター派遣率98.3%", "24時間365日対応", "産後ケア・新生児ケアにも対応", "年間10,000件以上の実績"],
    availableNow: 8,
    availableToday: 20,
    availableTomorrow: 30,
    operatingHours: "24時間365日対応",
    cancellationPolicy: "3時間前まで無料、3時間以内は100%。前日オーダー手数料1,500円、当日は3,000円",
    insurance: "賠償責任保険加入済み",
    url: "https://www.leange.co.jp"
  },
  {
    id: 4,
    name: "ミラクスシッター",
    logo: "MS",
    logoColor: "#FD7272",
    description: "30年の歴史ある派遣型サービス。病児ケア専用コースあり。24時間365日対応。",
    pricePerHour: 2750,
    minimumHours: 3,
    registrationFee: 33000,
    annualFee: 13200,
    rating: 4.5,
    reviewCount: 1800,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["保育士資格", "病児保育", "送迎あり", "当日予約OK"],
    features: ["30年の歴史ある信頼の派遣型サービス", "病児ケア専用コースあり", "マザーヘルパーコース（産前産後ケア）あり", "厳しい選考基準を通過したシッターのみ在籍", "24時間365日対応体制"],
    availableNow: 6,
    availableToday: 15,
    availableTomorrow: 25,
    operatingHours: "24時間365日対応",
    cancellationPolicy: "7日前〜2営業日前まで550円、前日50%、当日100%",
    insurance: "賠償責任保険加入済み",
    url: "https://sitter.miraxs.co.jp"
  },
  {
    id: 5,
    name: "ハニークローバー",
    logo: "HC",
    logoColor: "#FECA57",
    description: "派遣型とマッチング型の2種類から選べる。生後6日から対応可能。見守りカメラ導入で安心。",
    pricePerHour: 2800,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.4,
    reviewCount: 1200,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "生後6日〜12歳",
    tags: ["保育士資格", "病児保育", "送迎あり"],
    features: ["派遣型とマッチング型の2種類から選べる", "生後6日から対応可能（退院直後からOK）", "見守りカメラ（ベビーモニター）を導入", "病児保育に対応", "防災対策・ケガ防止の安全チェックを実施"],
    availableNow: 5,
    availableToday: 12,
    availableTomorrow: 20,
    operatingHours: "24時間対応",
    cancellationPolicy: "シッター連絡前は無料、1営業日前8:00〜18:00は50%、18:00以降は100%",
    insurance: "賠償責任保険加入済み",
    url: "https://sitter.honeyclover.co.jp"
  },
  {
    id: 6,
    name: "リトルハグ",
    logo: "LH",
    logoColor: "#45B7D1",
    description: "英語ベビーシッター専門サービス。外国人シッター多数在籍。「英会話de保育」がコンセプト。",
    pricePerHour: 3520,
    minimumHours: 3,
    registrationFee: 33000,
    annualFee: 5500,
    rating: 4.6,
    reviewCount: 950,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["英語対応", "送迎あり"],
    features: ["英語ベビーシッター専門サービス", "外国人・バイリンガルシッター多数在籍", "「英会話de保育」で遊びながら英語習得", "帰国子女の英語力維持にも活用可能", "トライアルプランでお試し利用が可能"],
    availableNow: 4,
    availableToday: 10,
    availableTomorrow: 18,
    operatingHours: "24時間365日対応",
    cancellationPolicy: "2営業日前18時まで無料、1営業日前18時まで50%、以降100%",
    insurance: "賠償責任保険加入済み",
    url: "https://littlehug.co.jp"
  },
  {
    id: 7,
    name: "ベビーシッターのHAS",
    logo: "HS",
    logoColor: "#E17055",
    description: "小学館集英社プロダクション（ShoPro）グループ運営。教育サービスや宿題補助にも対応。",
    pricePerHour: 2100,
    minimumHours: 2,
    registrationFee: 22000,
    annualFee: 10000,
    rating: 4.5,
    reviewCount: 2200,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜12歳",
    tags: ["保育士資格", "送迎あり"],
    features: ["小学館集英社プロダクション運営の高い信頼性", "教育サービス（宿題補助・習い事サポート）あり", "産前・産後ケアに対応", "充実した登録研修・救急救命講習を実施", "Web予約システムで24時間予約可能"],
    availableNow: 7,
    availableToday: 18,
    availableTomorrow: 28,
    operatingHours: "電話受付 平日9:00〜18:00 / Web予約は24時間",
    cancellationPolicy: "公式サイトにてご確認ください",
    insurance: "賠償責任保険加入済み",
    url: "https://hoiku.shopro.co.jp/babysitter/"
  },
  {
    id: 8,
    name: "マザーネット",
    logo: "MN",
    logoColor: "#00B894",
    description: "創業2000年、累計5万世帯以上の実績。病児保育・家事代行にも対応。30〜60代のベテランケアリストが中心。",
    pricePerHour: 2576,
    minimumHours: 2,
    registrationFee: 0,
    annualFee: 0,
    rating: 4.4,
    reviewCount: 3200,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "生後6ヶ月〜中学3年生",
    tags: ["保育士資格", "病児保育", "家事代行", "送迎あり"],
    features: ["創業2000年、累計5万世帯以上の実績", "病児保育対応（インフルエンザ含む感染症OK）", "家事代行も同料金で依頼可能", "30〜60代のベテラン主婦ケアリストが中心", "最短翌日から利用開始可能"],
    availableNow: 8,
    availableToday: 20,
    availableTomorrow: 32,
    operatingHours: "8:00〜20:00（年中無休）",
    cancellationPolicy: "キャンセル料は最低2,310円。詳細は公式サイトにてご確認ください",
    insurance: "お子様の保険加入あり（1日209円/人）",
    url: "https://www.mothernet.co.jp"
  },
  {
    id: 9,
    name: "ラビットクラブ",
    logo: "RC",
    logoColor: "#A29BFE",
    description: "30年以上の歴史、全国47都道府県に展開。コーディネーター制でプロが最適なシッターを選定。",
    pricePerHour: 1700,
    minimumHours: 2,
    registrationFee: 15000,
    annualFee: 5000,
    rating: 4.3,
    reviewCount: 4500,
    areas: ["渋谷区", "新宿区", "港区", "目黒区", "世田谷区", "品川区", "中央区", "千代田区", "文京区", "豊島区", "杉並区", "練馬区", "江東区", "大田区"],
    ageRange: "0歳〜9歳",
    tags: ["保育士資格", "病児保育", "送迎あり"],
    features: ["30年以上の歴史、全国47都道府県に展開", "コーディネーター制でプロが最適なシッターを選定", "独自カルテ「おかあさんメモ」と報告書「ラビットレポート」", "24時間365日対応・トラブルダイヤル完備", "入会前に自宅訪問でサービス説明あり"],
    availableNow: 10,
    availableToday: 22,
    availableTomorrow: 35,
    operatingHours: "24時間365日対応",
    cancellationPolicy: "当日の利用時間短縮は当初の予約時間での料金請求",
    insurance: "傷害保険・賠償責任保険加入済み",
    url: "https://www.rabi-popo.com/rabbitclub/"
  }
];
